DATA:
  IMG_SIZE: 384
  DATASET: 'food500'
MODEL:
  TYPE: swin_mg
  NAME: swin_mg-food500-lr7
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 7e-4
  BASE_LR: 7e-4
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False