MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 5e-5
  BASE_LR: 5e-04
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07